records:
  - id: ndu_aleph001890313
    title: The catcher in the rye
    description: Book with multiple identifiers, hierarchical subjects, and 5 frbr results.
  - id: ndu_aleph003261780
    title: Salinger's The catcher in the rye
    description: Book with online access and print available. Online access to just a table of contents.
  - id: ndu_aleph001753442
    title: Beethoven
    description: Audio with a lot of uniform/related titles. Series links with a volume number. Contents.  Multiple contributors.
  - id: ndu_aleph003119742
    title: Harry Potter and the Deathly Hallows. Part 2
    description: Video with a lot of contributors and a lot of subjects.
  - id: ndu_aleph002170825
    title: New scientist
    description: Journal with a lot of online links and volumes.
  - id: TN_gale_ofa277204662
    title: Firing on all synapses.(feature articles that have been covered by New Scientist)
    description: Primo Central Journal. ispartof key.
  - id: ndu_aleph003418217
    title: Beowulf
    description: Multiple languages. lds05
  - id: "TN_mla2008381166"
    title: "Chapter: Catcher in the Rye"
    description: "Book chapter with the findtext link."
  - id: ndu_aleph003618300
    title: The Transformation of magic...
    description: e-book that makes use of the proxy server.  Also potential link titling work.
  - id: ndu_aleph002072723
    title: American Journal of Theology
    description: because it is a complicated record
  - id: TN_gale_ofa246103668
    title: "'Voldemort' tries to salve worries over tenure issue"
    description: Record with FindText tab
  - id: ndu_aleph002808607
    title: "Government finance stats"
    description: Gov doc with some extra fields and a link with descriptive text.
  - id: ndu_aleph003030037
    title: "The little data book. 2008"
    description: Findtext redirect weirdness
  - id: ndu_aleph003407084
    title: "Tomodachi"
    description: Vernacular Title
  - id: hathi_pubMIU01-001593127
    title: "A list of emigrant..."
    description: Hathi Trust book.
  - id: dedupmrg97328716
    title: "The hunting of the snark"
    description: Complicated Hathi book
  - id: bci_aleph000133859
    title: "Pacifica review peace, security & global change."
    description: Bethel College record
  - id: ndu_aleph003607256
    title: "JSTOR ebook collection"
    description: uses eresources.library.nd.edu as a redirect to the proxied resource
  - id: ndu_aleph001300212
    title: "The State of Small Busineess"
    description: Super complicated titling history.
  - id: TN_gale_ofg16841917
    title: "Constantine XI Paleologos"
    description: Record with Findtext tab and onshelf access.
  - id: ndu_aleph001600269
    title: Apokalypse der deutschen Seele
    description: Multivolume in German


