development:
  token: discover
  url: http://localhost:3005
test:
  token: discover
  url: http://localhost:3005
pre_production:
  token: qtyZ5f6GrM67WWteGFp1
  url: https://apipprd.library.nd.edu
production:
  token: C6epGyym6ynWy3gfJett
  url: https://api.library.nd.edu
