development:
  token: whatever
  url: http://localhost:3005
test:
  token: qtyZ5f6GrM67WWteGFp1
  url: http://localhost:3005
pre_production:
  token: qtyZ5f6GrM67WWteGFp1
  url: https://apipprd.library.nd.edu
production:
  token: not_a_token
  url: https://apipprd.library.nd.edu
