development:
  token: qtyZ5f6GrM67WWteGFp1
  url: https://apipprd.library.nd.edu
test:
  token: qtyZ5f6GrM67WWteGFp1
  url: https://apipprd.library.nd.edu
pre_production:
  token: qtyZ5f6GrM67WWteGFp1
  url: https://apipprd.library.nd.edu
production:
  token: not_a_token
  url: https://apipprd.library.nd.edu
