default: &default
  host: 'primo-fe1.library.nd.edu:1701'
  vids:
    NDU:
      tabs:
        - nd_campus
        - onesearch
        - ebooks
      advanced_search:
        scope_name: 16833817UI0
    BCI:
      tabs:
        - onesearch
        - bci
        - malc
      advanced_search:
        scope_name: 16833526UI0
    HCC:
      tabs:
        - hcc
        - malc
      advanced_search:
        scope_name: 16833755UI0
    SMC:
      tabs:
        - onesearch
        - smc
        - malc
      advanced_search:
        scope_name: 16833813UI0

development:
  <<: *default

test:
  <<: *default

pre_production:
  <<: *default

production:
  <<: *default
