# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c9fddc8798f89f4ddd65c377d850b0ef9b420f576a577fc6157c96651cd81513584963a500c2779486cad19a571132f02c7c81f51e2cc1ea39c95d58f424bc
  database:
    :host: localhost
    :name: discovery_test
    :username: root
    :password:

test:
  secret_key_base: 02c9fddc8798f89f4ddd65c377d850b0ef9b420f576a577fc6157c96651cd81513584963a500c2779486cad19a571132f02c7c81f51e2cc1ea39c95d58f424bc
  database:
    :host: localhost
    :name: discovery_test
    :username: root
    :password:

pre_production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :host: #fill in
    :name: #fill in
    :username: #fill in
    :password: #fill in

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :host: #fill in
    :name: #fill in
    :username: #fill in
    :password: #fill in
